# Generated by Django 4.0.5 on 2022-06-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='Yrityksen nimi', max_length=50)),
                ('contactname', models.CharField(default='Yhteyshenkilö', max_length=50)),
                ('address', models.CharField(default='Osoite', max_length=100)),
                ('phone', models.CharField(default='Puhelin', max_length=20)),
                ('email', models.CharField(default='Sähköposti', max_length=50)),
                ('country', models.CharField(default='Maa', max_length=50)),
            ],
            options={
                'ordering': ['companyname'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Etunimi', max_length=50)),
                ('lastname', models.CharField(default='Sukunimi', max_length=50)),
                ('email', models.CharField(default='Sähköposti', max_length=50)),
                ('username', models.CharField(default='Käyttäjänimi', max_length=50)),
                ('password', models.CharField(default='Salasana', max_length=50)),
                ('accesslevelid', models.IntegerField(default=2)),
            ],
            options={
                'ordering': ['firstname'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='Tuote nimi', max_length=20)),
                ('packagesize', models.CharField(default=1, max_length=20)),
                ('unitprice', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('unitsinstock', models.IntegerField(default=1)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
            options={
                'ordering': ['productname'],
            },
        ),
    ]
